-- Execute no SQL Editor caso a tabela exista mas ainda nao permita leitura pelo painel.
begin;
create table if not exists public.atividade_sensor (
  id bigint generated by default as identity primary key,
  data_hora timestamptz
);
create index if not exists atividade_sensor_data_hora_idx
  on public.atividade_sensor (data_hora desc nulls last, id desc);
alter table public.atividade_sensor enable row level security;
grant select on public.atividade_sensor to anon, authenticated;
drop policy if exists "Dashboard can read inactivity" on public.atividade_sensor;
create policy "Dashboard can read inactivity"
  on public.atividade_sensor for select to anon, authenticated using (true);
commit;
