-- Execute no SQL Editor do seu projeto Supabase.
-- Contrato do firmware ESP32 para registrar deteccoes na tabela eventos.
begin;

drop table if exists public.sensor_state;
drop function if exists public.touch_sensor_state_updated_at();

create table if not exists public.eventos (
  id bigint generated by default as identity primary key,
  numero_evento bigint,
  data_hora text
);

create index if not exists eventos_id_desc_idx
  on public.eventos (id desc);

alter table public.eventos enable row level security;

revoke all on public.eventos from anon, authenticated;
grant select on public.eventos to anon, authenticated;
grant insert (numero_evento, data_hora) on public.eventos to anon;

drop policy if exists "Academic dashboard can read events" on public.eventos;
create policy "Academic dashboard can read events"
  on public.eventos for select to anon, authenticated
  using (true);

drop policy if exists "ESP32 can insert events" on public.eventos;
create policy "ESP32 can insert events"
  on public.eventos for insert to anon
  with check (
    numero_evento is not null
    and numero_evento >= 1
    and data_hora is not null
    and data_hora ~ '^(data_indisponivel|[0-9]{2}/[0-9]{2}/[0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2})$'
  );

do $$
declare
  identity_sequence text := pg_get_serial_sequence('public.eventos', 'id');
begin
  if identity_sequence is not null then
    execute format('grant usage on sequence %s to anon', identity_sequence);
  end if;
end $$;

commit;

-- A política anon permite que qualquer pessoa com a chave pública envie eventos.
-- Não use a chave service_role no firmware; para produção, use autenticação ou uma Edge Function.
