-- Leitura do ultimo estado informado pelo ESP32. Preserva registros existentes.
begin;
create table if not exists public.status_dispositivo (
  id bigint generated by default as identity primary key,
  data_hora timestamptz,
  status text
);
create index if not exists status_dispositivo_data_hora_idx
  on public.status_dispositivo (data_hora desc nulls last, id desc);
alter table public.status_dispositivo enable row level security;
grant select on public.status_dispositivo to anon, authenticated;
drop policy if exists "Dashboard can read device status" on public.status_dispositivo;
create policy "Dashboard can read device status"
  on public.status_dispositivo for select to anon, authenticated using (true);
commit;
